config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :abilities
  resources :characters
  resources :costumes
  resources :sessions
  resources :users do
    resources :avatars
  end

  post'/users/:id/avatars/:id/like', to: 'avatars#likes', as: 'like'
  root 'avatars#home', as: 'home'
  post '/avatars/:avatar_id/comments', to: 'comments#create', as: 'create_comment'
  delete '/logout', to: 'session#destroy', as: 'logout'

  ##STATIC
  root to: 'static#home'
  get '/about', to: 'static#about'
  get '/contact', to: 'static#contact'
  get '/faq', to: 'static#faq'
  get '/forum', to: 'static#forum'



##
# authenticate :user do
#   root to: 'home#index', as: :authenticated_root
# end
# root to: redirect('/users/sign_in')
end

app/models/ability.rb
class Ability < ApplicationRecord
  has_many :characters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :user
  belongs_to :character
  belongs_to :costume
  has_many :comments
  belongs_to :ability

  validates :name, uniqueness: { case_sensitive: false }




  def image
    if self.character_id == 1 && self.costume_id == 1
       "mario_summer.png"
    elsif self.character_id == 1 && self.costume_id == 2
      "mario_winter.jpg"
    elsif self.character_id == 1 && self.costume_id == 3
      "mario_halloween.jpeg"
    elsif self.character_id == 1 && self.costume_id == 4
      "street_mario.jpg"
    elsif self.character_id == 2 && self.costume_id == 1
      "princess_peach_summer.png"
    elsif self.character_id == 2 && self.costume_id == 2
      "princess_peach_winter.png"
    elsif self.character_id == 2 && self.costume_id == 3
      "mario_street_wear.png"
    elsif self.character_id == 2 && self.costume_id == 4
      "street_peach.jpg"
    end
  end



  def user_avatars_id
    @avatars = self.user.avatars.map(&:id)
  end

    def next_avatar
      current_index = user_avatars_id.index(self.id)
      if self.user.avatars[current_index + 1]
        @avatar = self.user.avatars[current_index + 1]
      else
        @avatar = self.user.avatars[current_index]
      end
    end

  def previous_avatar
    current_index = user_avatars_id.index(self.id)
    if current_index > 0
      @avatar = self.user.avatars[current_index - 1]
    else
      @avatar = self.user.avatars[current_index]
    end
  end
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :avatars
  has_many :users, through: :avatars
  has_many :costumes, through: :avatars
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :avatar
  belongs_to :user
end

app/models/costume.rb
class Costume < ApplicationRecord
  has_many :avatars
  has_many :users, through: :avatars
  has_many :characters, through: :avatars
end

app/models/user.rb
class User < ApplicationRecord
  has_many :avatars
  has_many :characters, through: :avatars
  has_many :costumes, through: :avatars
  has_many :comments
  has_secure_password

  validates :username, uniqueness: { case_sensitive: false }
  validates :password, length: {minimum: 3}
  validates :name, presence: true
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#   before_action :authorize
  helper_method :current_user

  def current_user
    if session[:user_id]
      @log_in_user = User.find_by(id: session[:user_id])
    else
    end
  end

  def logged_in?
    !!current_user
  end

  def authorize
    redirect_to login_path unless logged_in?
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @avatars = @user.avatars
    end

  def show
    @avatar = Avatar.find(params[:id])
    @comment = Comment.new(avatar_id: @avatar.id, user_id: @avatar.user.id)
  end

  def new
    if current_user == nil
      redirect_to home_path
    end
  @avatar = Avatar.new
  end


def create
   @avatar = Avatar.new(avatar_params)
   @avatar.user_id = current_user.id
   if @avatar
     @avatar.save
    redirect_to user_avatar_path(@avatar.user, @avatar)
  else
    render :new
   end
 end


  def edit
    @avatar = Avatar.find(params[:id])
  end

  def update
    @avatar = Avatar.find(params[:id])
    @avatar.update(avatar_params)
    if @avatar.update(avatar_params)
      redirect_to user_avatar_path(@avatar.user, @avatar)
    else
      render :edit
    end
  end

   def likes
     @avatar = Avatar.find(params[:id])
     @like = @avatar.likes + 1
     @avatar.update(likes: @like)
     redirect_to user_avatar_path(@avatar.user, @avatar)
   end

   def home
     @avatars = Avatar.all
   end

   def destroy
     @avatars = Avatar.find(params[:id]).destroy
     redirect_to user_avatars_path
   end


   private

   def find_user
     @user = User.find(params[:user_id])
   end

   def set_avatar
      @avatar = Avatar.find(params[:id])
    end

   def avatar_params
     params.require(:avatar).permit(:name, :likes, :costume_id, :user_id, :character_id, :ability_id)
   end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comment = Comment.all
  end

  def new
    @comment = Comment.new(comment_params)
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.avatar_id = params[:avatar_id]
     if @comment.valid?
       @comment.save
       redirect_to user_avatar_path(@comment.user_id, @comment.avatar_id)
     else
       render :new
     end
   end

   def destroy
     @comment = Comment.find(params[:id]).destroy
     redirect_to user_avatar_path(@comment.user, @comment.avatar)
   end



  private


  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController

  def index
    @costumes = Costume.all
  end

  def show
    @costume = Costume.find(params[:id])
  end

  def edit
    @costume = Costume.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home

  end

  def contact

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def index
      @users = User.all

    end

    def show
      @user = User.find(params[:id])

    end

    def edit

    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
       if @user.valid?
         @user.save
         session[:user_id] = @user.id
         flash[:notice] = "Sucessfully created an account"
        redirect_to user_path(@user)
      else
        render :new
       end
     end

    def update
      if User.update(user_params)
      redirect_to @user
      else
         render :edit
       end
    end

    def destroy
      @user = User.find(params[:id])
      @user.avatars.each do |avatar|
        avatar.destroy
      end
      @user.destroy
      redirect_to users_path
    end


  private

    def user_params
      params.require(:user).permit(:name, :bio, :location, :age, :username, :password)
    end

end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/costumes_helper.rb
module CostumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/avatars/_form.html.erb
<%= form_for @avatar, url: user_avatar_path do |f| %>
  <% if @avatar.errors.any? %>
    <% @avatar.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
      <% end %>
    <% end %>

 First name: <%= f.text_field :name %><br>
 Costume Name: <%= f.collection_select(:costume_id, Costume.all, :id, :name) %><br>
 Character Name: <%= f.collection_select(:character_id, Character.all, :id, :name) %><br>
 <%= f.submit %>
<% end %>

app/views/avatars/edit.html.erb
<h1>Edit your Avatar</h1>

<%= form_for @avatar, url: user_avatar_path do |f| %>
  <% if @avatar.errors.any? %>
    <% @avatar.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
      <% end %>
    <% end %>

 First name: <%= f.text_field :name %><br>
 Costume Name: <%= f.collection_select(:costume_id, Costume.all, :id, :name) %><br>
 Character Name: <%= f.collection_select(:character_id, Character.all, :id, :name) %><br>
 <%= f.submit %>
<% end %>

app/views/avatars/home.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.css">
  <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.js"></script>
  <style>
    .card{
      float: left;
    }
  </style>
</head>
<body>
  <% @avatars.sort_by{|avatar| avatar.likes}.reverse.each do |avatar| %>
    <div class="ui card">
      <%= link_to image_tag(avatar.image, alt: "avatar pic", height: 142, width: 142,:class => "style_image"), user_avatar_path(avatar.user, avatar) %>
      <div class="content"> Creator: <%= avatar.user.name %> <br>
      Likes: <%= avatar.likes %>   </div>

    </div>
  <% end %>


</body>
</html>

app/views/avatars/index.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

  <h1>All of Your Avatars </h1>
  <% if current_user %>
  <%= link_to "Create Avatar", new_user_avatar_path %> <br>
  <% end %>
  <%@avatars.each do |avatar|%>
    <%=link_to avatar.name, user_avatar_path(@user, avatar)%> <br>
  <%end%>

</body>
</html>

app/views/avatars/new.html.erb
<h3>This is where we create new avatars</h3>

<%= form_for @avatar, url: user_avatars_path do |f| %>
  <% if @avatar.errors.any? %>
    <% @avatar.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
      <% end %>
    <% end %>

 First name: <%= f.text_field :name %><br>
 Costume Name: <%= f.collection_select(:costume_id, Costume.all, :id, :name) %><br>
 Character Name: <%= f.collection_select(:character_id, Character.all, :id, :name) %><br>
 Ability <%= f.collection_select(:ability_id, Ability.all, :id, :name) %><br>
 <%= f.submit %>
<% end %>

app/views/avatars/show.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.css">
  <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.js"></script>
  <style>
  .wrapper {
    padding-left: 20px;
    padding-right: 20px;
  }

  .head {
    padding-left: 400px;
  }

  .features {
    float:left;
  }

  </style>
  <title><%= @avatar.name %></title>
</head>
<body>

    <div class='wrapper'>

  <div class= "features">
  <h3>Likes: <%=@avatar.likes%></h3>
    <%= image_tag @avatar.image, alt: "avatar pic", height: 200, width: 200,:class => "style_image" %> <br>
    <button> <%= link_to "Previous Avatar", user_avatar_path(@avatar.previous_avatar.user, @avatar.previous_avatar) %></button>
    <button> <%= link_to "Next Avatar", user_avatar_path(@avatar.next_avatar.user, @avatar.next_avatar) %></button> <br>
    <button><%= link_to "All #{@avatar.user.name} Avatar", user_avatars_path  %></button> <br>
    <% if current_user != nil %>
    <%=button_to ("Add Likes"), like_path%>
    <% if @avatar.user == current_user %>
    <button><%= link_to "Edit Avatar", edit_user_avatar_path(@avatar.user, @avatar) %></button>
    <%= button_to "delete", user_avatar_path(@avatar.user, @avatar), :method => :delete %>
    <% end %>
    <%= form_for @comment, url: create_comment_path(@avatar.id) do |f| %>
    <div><%= f.label :content %> </div>
    <%= f.text_area :content %>
    <%= f.submit "Save Comment" %>
    <% end %>
    <% end %>
    <br>
  </div>
</div>


    <div class="ui comments">
      <h3 class= "head" align="right">Comments</h3>
      <div class= 'bod'> </div>


  <%@avatar.comments.last(7).each do |comment| %>
<div class="comment">
<a class="avatar">

</a>
<div class="content hi" align="right">
  <a class="author"><%= comment.user.name %></a>
  <!-- <br> -->
  <div class="text hi" >
    <%= comment.content %>
  </div>
</div>
  <!-- <div class="text hi">
    <%= comment.content %>
  </div> -->
<!-- </div> -->
</div>

<% end %>







<table class="ui definition table">
  <tbody>
    <tr>
      <td class="two wide column">Name</td>
      <td><%= @avatar.name %></td>
    </tr>
    <tr>
      <td>Creator</td>
      <td><%= link_to @avatar.user.username, @avatar.user%></td>
    </tr>
    <tr>
      <td>Costume</td>
      <td><%=@avatar.costume.name%></td>
    </tr>
    <tr>
      <td>Character</td>
      <td><%=@avatar.character.name%></td>
    </tr>
    <tr>
      <td>Ability</td>
      <td><%= @avatar.ability.name %></td>
    </tr>
  </tbody>
</table>
</div>
</body>
</html>

app/views/costumes/index.html.erb
<h1>Here are some of the available costumes. THERE ARE MANY MORE TO COME</h1>
<%@costumes.all.each do |costume| %>
<p> <%=link_to costume.name, costumes_path %> </p>
<p> img </p>
<br>
<%end%>

app/views/users/_form.html.erb
<!-- <h3>This is where we create new avatars</h3>
 <%= form_for @avatar do |f| %>
  First name: <%= f.text_field :name %><br>
  Last name: <%= f.text_field :likes %><br>
  Costume ID: <%= f.collection_select(:costume_id, Costume.all, :id, :name) %><br>
  Character ID: <%= f.collection_select(:character_id, Character.all, :id, :name) %><br>
  User ID: <%= f.collection_select(:user_id, User.all, :id, :name) %><br>

  <%= f.submit %>
<% end %> -->

app/views/users/index.html.erb
 <h1> List of Users
  <ol>
    <%@users.each do |user|%></h1>
<li><%=link_to user.name, user_path(user.id)%></li>
<%end%>
</ol>

app/views/users/new.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <style>
    .wrapper {
      padding-left: 15px;
    }
  </style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.css">
  <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.js"></script>
  <title>Document</title>
</head>
<body>
<div class="wrapper">
 <div class="center">
    <h2>Sign up</h2>
    <%= form_for(@user) do |f| %>
      <%= f.text_field :username, placeholder: "username*" %><br>
      <%= f.password_field :password, placeholder: "Password*" %><br>
      <%= f.text_field :name, placeholder: "name*" %><br>
      <%= f.text_field :location, placeholder: "Location*" %><br>
      <%= f.number_field :age, placeholder: "age", autofocus: true %><br>
      <%= f.text_area :bio, placeholder: "bio" %><br>
        <div><%= f.submit "Sign up", class: "btn btn-large btn-primary" %></div>
        <% end %>
  </div>
</div>

app/views/users/show.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>User Avatar</title>
  <style>
    .style_image{
      border: 1px solid black;
      padding: 15px;
    }
  </style>
</head>
<body>
  <h1><%= @user.name %></h1>




  <%@user.avatars.each do |avatar|%>
  <%= link_to image_tag(avatar.image, alt: "avatar pic", height: 142, width: 142,:class => "style_image"), user_avatar_path(avatar.user, avatar) %>
  <%end%> <br>
    <%if current_user.nil?  %>
  <% else current_user.id == @user.id %>
    <%= link_to "Create Avatar", new_user_avatar_path(@user) %>
    <%= button_to "Log Out", session_path("hello"), method: :delete %> </a>
    <%= button_to "Delete Account", @user, :method => :delete,  data: {confirm: "Are you sure?"} %>
  <% end %>

</body>
</html>